### ISSUE TITLE
홈 탭 페이지 수정사항

### ISSUE THREAD

**Issue by Huijiny** [mash-up-kr/chinchin-android#57]
- [x] 종 아이콘 추가
- [x] 친친 아이콘 추가 
- [x] 가이드 폰트 다름 추가
- [x] 그룹추가 버튼이랑 리스트 떨어트리기
~원형 이미지 겹치기~

**Comment by AnKyungMoo** [comment]
원형 이미지 겹치기는 나중에.. 하는걸로 ㅎ..
