### ISSUE TITLE
친구 디테일 페이지

### ISSUE THREAD

**Issue by hj1115hj** [mash-up-kr/chinchin-android#69]
- 친구 디테일 페이지(가입자 미가입자 다름 주의해서 체크해)
    - 친구이름이랑 친구 생일 padding
    - 탭 인디케이터 (밑줄)
    - 총 질문 → 총 답변 문구 변경
    - 친구 답변, 내 답변 문구 변경
    - ~~empty 일러스트~~
    - 총 답변 horizontal padding
    - 질문추가 뭐야;;;;; 있는기준이 뭐야
    - collapsed scroll

**Comment by AnKyungMoo** [comment]
디자인이 전체적으로 수정될 예정입니당
